-- Expert Q&A articles for expert-led editorial content.
-- This migration only creates tables and policies. Run it from Supabase SQL Editor
-- or the Supabase CLI after reviewing the target project schema.

create table if not exists public.expert_articles (
  id bigint generated by default as identity primary key,
  expert_id uuid null,
  title text not null,
  slug text not null unique,
  summary text null,
  lead_text text null,
  content_json jsonb not null default '{}'::jsonb,
  content_html text null,
  closing_text text null,
  main_image_url text null,
  meta_title text null,
  meta_description text null,
  generation_mode text not null default 'manual',
  verification_status text not null default 'operator_created',
  status text not null default 'draft',
  is_active boolean not null default true,
  published_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint expert_articles_generation_mode_check
    check (generation_mode in ('manual', 'ai_interview')),
  constraint expert_articles_verification_status_check
    check (verification_status in ('operator_created', 'ai_generated', 'expert_reviewed', 'expert_supervised')),
  constraint expert_articles_status_check
    check (status in ('draft', 'published', 'archived'))
);

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'experts'
  ) and not exists (
    select 1
    from pg_constraint
    where conname = 'expert_articles_expert_id_fkey'
  ) then
    alter table public.expert_articles
      add constraint expert_articles_expert_id_fkey
      foreign key (expert_id)
      references public.experts(id)
      on delete set null;
  end if;
end $$;

create table if not exists public.expert_article_subsidies (
  id bigint generated by default as identity primary key,
  expert_article_id bigint not null references public.expert_articles(id) on delete cascade,
  subsidy_id bigint not null references public.subsidies(id) on delete cascade,
  sort_order integer not null default 0,
  note text null,
  created_at timestamptz not null default now(),
  unique (expert_article_id, subsidy_id)
);

create index if not exists idx_expert_articles_public
  on public.expert_articles (status, is_active, published_at desc);

create index if not exists idx_expert_articles_slug
  on public.expert_articles (slug);

create index if not exists idx_expert_article_subsidies_article
  on public.expert_article_subsidies (expert_article_id, sort_order);

create or replace function public.set_expert_articles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_expert_articles_updated_at on public.expert_articles;

create trigger set_expert_articles_updated_at
before update on public.expert_articles
for each row
execute function public.set_expert_articles_updated_at();

grant usage on schema public to anon, authenticated, service_role;

grant select on public.expert_articles to anon;
grant select on public.expert_article_subsidies to anon;

grant select, insert, update, delete on public.expert_articles to authenticated;
grant select, insert, update, delete on public.expert_article_subsidies to authenticated;

grant select, insert, update, delete on public.expert_articles to service_role;
grant select, insert, update, delete on public.expert_article_subsidies to service_role;

grant usage, select on all sequences in schema public to authenticated;
grant usage, select on all sequences in schema public to service_role;

alter table public.expert_articles enable row level security;
alter table public.expert_article_subsidies enable row level security;

drop policy if exists "public can read published expert articles" on public.expert_articles;
create policy "public can read published expert articles"
  on public.expert_articles
  for select
  to anon
  using (status = 'published' and is_active = true);

drop policy if exists "authenticated admins can manage expert articles" on public.expert_articles;
create policy "authenticated admins can manage expert articles"
  on public.expert_articles
  for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "public can read published expert article subsidies" on public.expert_article_subsidies;
create policy "public can read published expert article subsidies"
  on public.expert_article_subsidies
  for select
  to anon
  using (
    exists (
      select 1
      from public.expert_articles article
      where article.id = expert_article_id
        and article.status = 'published'
        and article.is_active = true
    )
  );

drop policy if exists "authenticated admins can manage expert article subsidies" on public.expert_article_subsidies;
create policy "authenticated admins can manage expert article subsidies"
  on public.expert_article_subsidies
  for all
  to authenticated
  using (true)
  with check (true);
