export const FEATURE_PAGES = [
  {
    slug: 'construction',
    path: '/feature/construction',
    title: '建設業・建築業の方必見',
    seoTitle: '建設業・建築業向け補助金・助成金｜愛媛県｜えひめ補助金ポータル',
    description:
      '愛媛県内の建設業・建築業・工務店・設備工事業の方が確認しておきたい補助金・助成金をまとめています。',
    h1: '建設業・建築業の方におすすめの補助金・助成金',
    leadText:
      '設備投資、省エネ、IT導入、人材確保、防災・BCP、事業承継など、建設関連事業者が活用しやすい制度を探せます。',
    targetKeywords: [
      '建設業',
      '建築業',
      '工務店',
      '設備工事',
      '設備投資',
      '省エネ',
      '人材育成・雇用',
      '生産性向上・業務効率化',
      '防犯・防災・BCP',
      '事業承継',
    ],
    purposeTags: [
      '設備投資',
      '省エネ',
      '人材育成・雇用',
      '生産性向上・業務効率化',
      '防犯・防災・BCP',
      '事業承継',
    ],
    industryTags: ['建設業'],
    searchKeywords: [
      '建設',
      '建築',
      '工務店',
      '設備工事',
      'BCP',
      '耐震',
      '改修',
    ],
    relatedFeatureSlugs: ['housing-renovation', 'energy-equipment', 'manufacturing'],
    icon: '🏗️',
    color: '#0f7b6c',
    priority: 100,
  },
  {
    slug: 'restaurant-retail',
    path: '/feature/restaurant-retail',
    title: '飲食店・小売店の方必見',
    seoTitle: '飲食店・小売店向け補助金・助成金｜愛媛県｜えひめ補助金ポータル',
    description:
      '愛媛県内の飲食店・小売店・店舗運営事業者の方が確認しておきたい補助金・助成金をまとめています。',
    h1: '飲食店・小売店の方におすすめの補助金・助成金',
    leadText:
      '店舗改装、販路開拓、省力化、デジタル化、キャッシュレス対応、省エネ設備の導入などに活用できる制度を探せます。',
    targetKeywords: [
      '飲食業',
      '小売業',
      '店舗改装',
      '販路開拓・販路拡大',
      '設備投資',
      '省力化・省人化',
      'デジタル',
      '省エネ',
    ],
    purposeTags: [
      '販路開拓・販路拡大',
      '設備投資',
      '省力化・省人化',
      'デジタル',
      '省エネ',
    ],
    industryTags: ['飲食業', '小売業'],
    searchKeywords: [
      '飲食店',
      '小売店',
      '店舗',
      'キャッシュレス',
      '店鋪改装',
      '販促',
    ],
    relatedFeatureSlugs: ['sales-channel', 'beauty-salon', 'energy-equipment'],
    icon: '🍽️',
    color: '#e76305',
    priority: 95,
  },
  {
    slug: 'startup-digital',
    path: '/feature/startup-digital',
    title: '創業・IT導入・DXをお考えの方へ',
    seoTitle: '創業・IT導入・DX向け補助金・助成金｜愛媛県｜えひめ補助金ポータル',
    description:
      '愛媛県内で創業・起業を考えている方、IT導入やDX、業務効率化を進めたい事業者向けの補助金・助成金をまとめています。',
    h1: '創業・IT導入・DXに使える補助金・助成金',
    leadText:
      'ホームページ制作、ECサイト、業務システム、クラウドツール、デジタル化、販路開拓などに関する制度を探せます。',
    targetKeywords: [
      '起業・創業・ベンチャー',
      'デジタル',
      '生産性向上・業務効率化',
      '販路開拓・販路拡大',
      '新規事業・第二創業',
      'IT',
      'DX',
    ],
    purposeTags: [
      '起業・創業・ベンチャー',
      'デジタル',
      '生産性向上・業務効率化',
      '販路開拓・販路拡大',
      '新規事業・第二創業',
    ],
    industryTags: ['情報通信業'],
    searchKeywords: [
      '創業',
      '起業',
      'ベンチャー',
      'IT',
      'DX',
      'ホームページ',
      'EC',
      'クラウド',
    ],
    relatedFeatureSlugs: ['sales-channel', 'manufacturing', 'restaurant-retail'],
    icon: '💻',
    color: '#2563eb',
    priority: 90,
  },
  {
    slug: 'manufacturing',
    path: '/feature/manufacturing',
    title: '製造業の方必見｜愛媛県で使える補助金・助成金特集',
    seoTitle: '製造業向け補助金・助成金｜愛媛県｜えひめ補助金ポータル',
    description:
      '愛媛県内の製造業・ものづくり事業者の方が確認しておきたい補助金・助成金をまとめています。',
    h1: '製造業の方におすすめの補助金・助成金',
    leadText:
      '設備投資、生産性向上、新商品開発、販路開拓、省エネ、DX、人材育成など、製造業で活用しやすい制度を探せます。',
    targetKeywords: [
      '製造業',
      'ものづくり',
      '設備投資',
      '生産性向上',
      '新商品開発',
      '販路開拓',
      '省エネ',
      'DX',
    ],
    purposeTags: [
      '設備投資',
      '生産性向上・業務効率化',
      'ものづくり・新商品開発',
      '販路開拓・販路拡大',
      '省エネ',
      'デジタル',
      '人材育成・雇用',
    ],
    industryTags: ['製造業', '食品製造業'],
    searchKeywords: ['製造', 'ものづくり', '工場', '生産設備', '新商品'],
    relatedFeatureSlugs: ['energy-equipment', 'sales-channel', 'startup-digital'],
    icon: '🏭',
    color: '#475569',
    priority: 88,
  },
  {
    slug: 'agriculture',
    path: '/feature/agriculture',
    title: '農業・就農者向け｜愛媛県で使える補助金・助成金特集',
    seoTitle: '農業・就農者向け補助金・助成金｜愛媛県｜えひめ補助金ポータル',
    description:
      '愛媛県内の農業者、農業法人、新規就農を検討している方が確認しておきたい補助金・助成金をまとめています。',
    h1: '農業・就農者の方におすすめの補助金・助成金',
    leadText:
      '農業設備、施設整備、販路開拓、スマート農業、6次産業化、担い手支援などに関する制度を探せます。',
    targetKeywords: [
      '農業',
      '農業者',
      '農業法人',
      '新規就農',
      'スマート農業',
      '施設整備',
      '6次産業化',
      '担い手',
    ],
    purposeTags: ['設備投資', '販路開拓・販路拡大', '新規事業・第二創業'],
    industryTags: ['農業', '畜産業', '林業', '漁業'],
    searchKeywords: ['農業', '農業法人', '就農', '担い手', 'スマート農業', '6次産業'],
    relatedFeatureSlugs: ['sales-channel', 'energy-equipment', 'manufacturing'],
    icon: '🌱',
    color: '#15803d',
    priority: 84,
  },
  {
    slug: 'tourism',
    path: '/feature/tourism',
    title: '宿泊業・観光業向け｜愛媛県で使える補助金・助成金特集',
    seoTitle: '宿泊業・観光業向け補助金・助成金｜愛媛県｜えひめ補助金ポータル',
    description:
      '愛媛県内のホテル、旅館、民宿、観光事業者、体験型サービス事業者の方が確認しておきたい補助金・助成金をまとめています。',
    h1: '宿泊業・観光業の方におすすめの補助金・助成金',
    leadText:
      '施設改修、インバウンド対応、観光コンテンツ造成、販路開拓、省エネ設備などに活用できる制度を探せます。',
    targetKeywords: [
      '宿泊業',
      '観光業',
      'ホテル',
      '旅館',
      '民宿',
      'インバウンド',
      '観光コンテンツ',
      '施設改修',
    ],
    purposeTags: ['観光・インバウンド', '設備投資', '販路開拓・販路拡大', '省エネ'],
    industryTags: ['宿泊業', 'サービス業'],
    searchKeywords: ['観光', '宿泊', 'ホテル', '旅館', '民宿', 'インバウンド'],
    relatedFeatureSlugs: ['restaurant-retail', 'sales-channel', 'energy-equipment'],
    icon: '🛎️',
    color: '#0369a1',
    priority: 78,
  },
  {
    slug: 'beauty-salon',
    path: '/feature/beauty-salon',
    title: '美容室・サロン向け｜愛媛県で使える補助金・助成金特集',
    seoTitle: '美容室・サロン向け補助金・助成金｜愛媛県｜えひめ補助金ポータル',
    description:
      '愛媛県内の美容室、理容室、エステ、整体、サロン運営者の方が確認しておきたい補助金・助成金をまとめています。',
    h1: '美容室・サロンの方におすすめの補助金・助成金',
    leadText:
      '店舗改装、設備導入、省エネ、キャッシュレス対応、ホームページ制作、販路開拓、集客支援などに関する制度を探せます。',
    targetKeywords: [
      '美容室',
      '理容室',
      'サロン',
      'エステ',
      '整体',
      '店舗改装',
      '設備導入',
      '集客',
    ],
    purposeTags: ['設備投資', '販路開拓・販路拡大', '省エネ', 'デジタル'],
    industryTags: ['サービス業'],
    searchKeywords: ['美容', '理容', 'サロン', 'エステ', '整体', '店舗改装', '集客'],
    relatedFeatureSlugs: ['restaurant-retail', 'sales-channel', 'energy-equipment'],
    icon: '✂️',
    color: '#be185d',
    priority: 72,
  },
  {
    slug: 'medical-welfare',
    path: '/feature/medical-welfare',
    title: '医療・福祉・介護向け｜愛媛県で使える補助金・助成金特集',
    seoTitle: '医療・福祉・介護向け補助金・助成金｜愛媛県｜えひめ補助金ポータル',
    description:
      '愛媛県内の医療機関、福祉施設、介護事業者、障がい福祉サービス事業者の方が確認しておきたい補助金・助成金をまとめています。',
    h1: '医療・福祉・介護事業者におすすめの補助金・助成金',
    leadText:
      '人材確保、設備導入、業務効率化、ICT導入、感染症対策、施設改修などに関する制度を探せます。',
    targetKeywords: [
      '医療',
      '福祉',
      '介護',
      '介護事業',
      '福祉施設',
      'ICT導入',
      '人材確保',
      '施設改修',
    ],
    purposeTags: ['人材育成・雇用', '設備投資', '生産性向上・業務効率化', 'デジタル'],
    industryTags: ['医療・福祉', '介護'],
    searchKeywords: ['医療', '福祉', '介護', '障がい', '障害', 'ICT', '感染症'],
    relatedFeatureSlugs: ['personal-assistance', 'childcare-family', 'energy-equipment'],
    icon: '🩺',
    color: '#7c3aed',
    priority: 70,
  },
  {
    slug: 'housing-renovation',
    path: '/feature/housing-renovation',
    title: '住宅・リフォーム・空き家活用向け｜愛媛県の補助金・助成金特集',
    seoTitle: '住宅・リフォーム・空き家活用の補助金・助成金｜愛媛県｜えひめ補助金ポータル',
    description:
      '愛媛県内で住宅改修、耐震改修、省エネ改修、空き家活用、移住・定住、リフォームを検討している方が確認しておきたい補助金・助成金をまとめています。',
    h1: '住宅・リフォーム・空き家活用に使える補助金・助成金',
    leadText: '個人向け・事業者向けの住宅関連支援制度を探せます。',
    targetKeywords: [
      '住宅',
      'リフォーム',
      '空き家',
      '耐震',
      '省エネ改修',
      '移住',
      '定住',
      '住宅改修',
    ],
    purposeTags: ['空き家利用', '省エネ', '設備投資'],
    industryTags: ['建設業'],
    searchKeywords: ['住宅', 'リフォーム', '空き家', '耐震', '移住', '定住', '改修'],
    relatedFeatureSlugs: ['construction', 'personal-assistance', 'energy-equipment'],
    icon: '🏠',
    color: '#b45309',
    priority: 82,
  },
  {
    slug: 'childcare-family',
    path: '/feature/childcare-family',
    title: '子育て世帯向け｜愛媛県で使える助成金・支援制度特集',
    seoTitle: '子育て世帯向け助成金・支援制度｜愛媛県｜えひめ補助金ポータル',
    description:
      '愛媛県内の子育て世帯、妊娠・出産・育児に関する支援を探している方が確認しておきたい助成金・支援制度をまとめています。',
    h1: '子育て世帯におすすめの助成金・支援制度',
    leadText:
      '医療費助成、子育て支援、出産関連助成、通院支援、家庭向け補助などの制度を探せます。',
    targetKeywords: [
      '子育て',
      '妊娠',
      '出産',
      '育児',
      '医療費助成',
      '子ども医療',
      '母子保健',
      '家庭向け支援',
    ],
    purposeTags: [],
    industryTags: ['医療・福祉'],
    searchKeywords: ['子育て', '妊娠', '出産', '育児', '子ども医療', '母子保健', '通院'],
    relatedFeatureSlugs: ['personal-assistance', 'medical-welfare', 'housing-renovation'],
    icon: '👪',
    color: '#db2777',
    priority: 80,
  },
  {
    slug: 'energy-equipment',
    path: '/feature/energy-equipment',
    title: '省エネ設備・脱炭素向け｜愛媛県で使える補助金・助成金特集',
    seoTitle: '省エネ設備・脱炭素向け補助金・助成金｜愛媛県｜えひめ補助金ポータル',
    description:
      '愛媛県内で省エネ設備、LED照明、高効率空調、太陽光発電、蓄電池、脱炭素投資を検討している事業者・個人の方が確認しておきたい補助金・助成金をまとめています。',
    h1: '省エネ設備・脱炭素に使える補助金・助成金',
    leadText: '設備投資や省エネ対策、ゼロカーボン関連の支援制度を探せます。',
    targetKeywords: [
      '省エネ',
      '脱炭素',
      'LED',
      '太陽光',
      '蓄電池',
      '高効率空調',
      '設備投資',
      'ゼロカーボン',
    ],
    purposeTags: ['省エネ', '再エネ・蓄エネ', '設備投資', '環境'],
    industryTags: [],
    searchKeywords: ['省エネ', '脱炭素', 'LED', '太陽光', '蓄電池', '空調', 'ゼロカーボン'],
    relatedFeatureSlugs: ['manufacturing', 'construction', 'housing-renovation'],
    icon: '💡',
    color: '#0f766e',
    priority: 86,
  },
  {
    slug: 'sales-channel',
    path: '/feature/sales-channel',
    title: '販路開拓・売上アップ向け｜愛媛県で使える補助金・助成金特集',
    seoTitle: '販路開拓・売上アップ向け補助金・助成金｜愛媛県｜えひめ補助金ポータル',
    description:
      '愛媛県内の事業者が販路開拓、売上拡大、展示会出展、ECサイト制作、広告宣伝、商品開発、海外展開などに活用できる補助金・助成金をまとめています。',
    h1: '販路開拓・売上アップに使える補助金・助成金',
    leadText: '売上拡大や新規顧客獲得に役立つ支援制度を探せます。',
    targetKeywords: [
      '販路開拓',
      '売上アップ',
      '展示会',
      'ECサイト',
      '広告宣伝',
      '商品開発',
      '海外展開',
      'マーケティング',
    ],
    purposeTags: [
      '販路開拓・販路拡大',
      'ものづくり・新商品開発',
      '海外展開',
      'デジタル',
    ],
    industryTags: [],
    searchKeywords: ['販路', '売上', '展示会', 'EC', '広告', '商品開発', '海外展開'],
    relatedFeatureSlugs: ['restaurant-retail', 'manufacturing', 'startup-digital'],
    icon: '📈',
    color: '#dc2626',
    priority: 76,
  },
  {
    slug: 'personal-assistance',
    path: '/feature/personal-assistance',
    title: '個人向け助成金・支援制度｜愛媛県で使える補助・助成特集',
    seoTitle: '個人向け助成金・支援制度｜愛媛県｜えひめ補助金ポータル',
    description:
      '愛媛県内で利用できる個人向けの助成金・支援制度をまとめています。',
    h1: '個人向けに使える助成金・支援制度',
    leadText:
      '子育て、医療費助成、不妊治療、住宅改修、移住・定住、福祉、通院支援など、暮らしに関わる支援制度を探せます。',
    targetKeywords: [
      '個人向け',
      '助成金',
      '医療費助成',
      '不妊治療',
      '子育て',
      '住宅改修',
      '移住',
      '福祉',
    ],
    purposeTags: [],
    industryTags: ['医療・福祉', '介護'],
    searchKeywords: [
      '個人向け',
      '医療費助成',
      '不妊治療',
      '子育て',
      '住宅改修',
      '移住',
      '福祉',
      '通院',
    ],
    relatedFeatureSlugs: ['childcare-family', 'housing-renovation', 'medical-welfare'],
    icon: '🤝',
    color: '#4f46e5',
    priority: 74,
  },
];

export const FEATURE_PAGE_GROUPS = [
  {
    title: '業種別特集',
    description: '業種に合わせて、確認しておきたい補助金・助成金を探せます。',
    slugs: [
      'construction',
      'restaurant-retail',
      'manufacturing',
      'agriculture',
      'tourism',
      'beauty-salon',
      'medical-welfare',
    ],
  },
  {
    title: '目的別特集',
    description: '設備投資、省エネ、販路開拓など、利用目的から支援制度を探せます。',
    slugs: ['startup-digital', 'energy-equipment', 'sales-channel', 'housing-renovation'],
  },
  {
    title: '個人向け支援',
    description: '子育て、医療、住宅、移住など暮らしに関わる支援制度を探せます。',
    slugs: ['childcare-family', 'personal-assistance'],
  },
];

export function getFeaturePageBySlug(slug) {
  return FEATURE_PAGES.find((feature) => feature.slug === slug);
}

export function getFeatureKeywords(feature) {
  return [
    ...(feature.targetKeywords || []),
    ...(feature.purposeTags || []),
    ...(feature.industryTags || []),
    ...(feature.searchKeywords || []),
  ].filter(Boolean);
}

export function getTopFeaturePages(limit = 6) {
  return [...FEATURE_PAGES].sort((a, b) => b.priority - a.priority).slice(0, limit);
}
