import fs from 'node:fs';
import path from 'node:path';
import { createClient } from '@supabase/supabase-js';
import { STATIC_SEO_COLUMNS } from '../src/staticSeoColumns.js';

const SITE_URL = normalizeSiteUrl(
  process.env.VITE_SITE_URL ||
    loadEnvValue('VITE_SITE_URL') ||
    'https://ehime-hojokin.jp'
);

const SUPABASE_URL =
  process.env.VITE_SUPABASE_URL ||
  loadEnvValue('VITE_SUPABASE_URL');

const SUPABASE_ANON_KEY =
  process.env.VITE_SUPABASE_ANON_KEY ||
  loadEnvValue('VITE_SUPABASE_ANON_KEY');

const OUTPUT_PATH = path.resolve('public/sitemap.xml');
const SUBSIDY_ROUTE_MAP_OUTPUT_PATH = path.resolve('public/subsidy-route-map.conf');

const FEATURE_ROUTES = [
  '/feature/construction',
  '/feature/restaurant-retail',
  '/feature/startup-digital',
  '/feature/sole-proprietor',
  '/feature/manufacturing',
  '/feature/agriculture',
  '/feature/tourism',
  '/feature/beauty-salon',
  '/feature/medical-welfare',
  '/feature/housing-renovation',
  '/feature/childcare-family',
  '/feature/energy-equipment',
  '/feature/sales-channel',
  '/feature/personal-assistance',
];

const STATIC_ROUTES = [
  { path: '/', changefreq: 'daily', priority: '1.0' },
  { path: '/ehime-subsidy/', changefreq: 'daily', priority: '0.9' },
  { path: '/simulator', changefreq: 'monthly', priority: '0.7' },
  { path: '/experts', changefreq: 'monthly', priority: '0.7' },
  { path: '/expert-articles', changefreq: 'weekly', priority: '0.75' },
  { path: '/beginners', changefreq: 'monthly', priority: '0.7' },
  { path: '/columns', changefreq: 'weekly', priority: '0.8' },
  { path: '/area/matsuyama', changefreq: 'daily', priority: '0.85' },
  { path: '/area/imabari', changefreq: 'daily', priority: '0.85' },
  { path: '/area/niihama', changefreq: 'daily', priority: '0.85' },
  { path: '/area/uwajima', changefreq: 'daily', priority: '0.85' },
  { path: '/area/seiyo', changefreq: 'daily', priority: '0.85' },
  { path: '/area/yawatahama', changefreq: 'daily', priority: '0.85' },
  { path: '/area/saijo', changefreq: 'daily', priority: '0.85' },
  { path: '/area/ozu', changefreq: 'daily', priority: '0.85' },
  { path: '/area/shikokuchuo', changefreq: 'daily', priority: '0.85' },
  { path: '/area/kumakogen', changefreq: 'daily', priority: '0.85' },
  { path: '/purpose/startup', changefreq: 'daily', priority: '0.85' },
  { path: '/purpose/energy-saving', changefreq: 'daily', priority: '0.85' },
  { path: '/purpose/digital', changefreq: 'daily', priority: '0.85' },
  { path: '/purpose/it-introduction', changefreq: 'daily', priority: '0.85' },
  { path: '/purpose/ai', changefreq: 'daily', priority: '0.85' },
  { path: '/purpose/sole-proprietor', changefreq: 'daily', priority: '0.85' },
  { path: '/purpose/benefits', changefreq: 'daily', priority: '0.85' },
  { path: '/purpose/childcare', changefreq: 'daily', priority: '0.85' },
  { path: '/purpose/housing', changefreq: 'daily', priority: '0.85' },
  { path: '/features', changefreq: 'weekly', priority: '0.85' },
  ...STATIC_SEO_COLUMNS.map((column) => ({
    path: `/column/${column.slug}`,
    changefreq: 'monthly',
    priority: '0.75',
  })),
  ...FEATURE_ROUTES.map((path) => ({
    path,
    changefreq: 'daily',
    priority: '0.85',
  })),
];

function normalizeSiteUrl(url) {
  return String(url || '').trim().replace(/\/+$/, '');
}

function escapeXml(value) {
  return String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function toIsoDate(value) {
  if (!value) return new Date().toISOString().slice(0, 10);

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return new Date().toISOString().slice(0, 10);

  return date.toISOString().slice(0, 10);
}

function buildUrl(pathname) {
  const normalizedPath = pathname.startsWith('/') ? pathname : `/${pathname}`;
  return `${SITE_URL}${normalizedPath}`;
}

function isIndexableSitemapPath(pathname) {
  const value = String(pathname || '').trim();
  if (!value) return false;

  const [pathOnly] = value.split('?');

  if (pathOnly === '/search') return false;
  if (value.includes('search?keyword=')) return false;
  if (value.includes('{search_term_string}')) return false;

  return true;
}

function isIndexableSubsidy(item) {
  if (!item?.id) return false;

  const text = [
    item.title,
    item.summary,
    item.organization,
  ]
    .filter(Boolean)
    .join(' ');

  return !/(申請練習用|練習用|ダミー|テスト|補助金の支払いはありません)/.test(text);
}

function writeSubsidyRouteMap(subsidies) {
  const ids = Array.from(
    new Set(
      subsidies
        .filter(isIndexableSubsidy)
        .map((item) => String(item.id).trim())
        .filter((id) => /^\d+$/.test(id))
    )
  ).sort((a, b) => Number(a) - Number(b));

  const content = [
    '# Generated by scripts/generate-sitemap.mjs.',
    '# Include this file in nginx http context to let unknown /subsidy/{id} URLs return 404.',
    'map $uri $ehime_subsidy_known_route {',
    '  default 0;',
    ...ids.map((id) => `  /subsidy/${id} 1;`),
    '}',
    '',
  ].join('\n');

  fs.writeFileSync(SUBSIDY_ROUTE_MAP_OUTPUT_PATH, content, 'utf8');

  return ids.length;
}

function toUrlEntry({ loc, lastmod, changefreq = 'weekly', priority = '0.6' }) {
  return `  <url>
    <loc>${escapeXml(loc)}</loc>
    <lastmod>${escapeXml(toIsoDate(lastmod))}</lastmod>
    <changefreq>${escapeXml(changefreq)}</changefreq>
    <priority>${escapeXml(priority)}</priority>
  </url>`;
}

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};

  const content = fs.readFileSync(filePath, 'utf8');
  const result = {};

  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!match) continue;

    const key = match[1];
    let value = match[2].trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    result[key] = value;
  }

  return result;
}

function loadEnvValue(key) {
  const envFiles = ['.env', '.env.local', '.env.production', '.env.production.local'];
  let value = '';

  for (const envFile of envFiles) {
    const parsed = parseEnvFile(path.resolve(envFile));
    if (parsed[key]) value = parsed[key];
  }

  return value;
}

async function fetchAllPublishedSubsidies(supabase) {
  const pageSize = 1000;
  let from = 0;
  const rows = [];

  while (true) {
    const to = from + pageSize - 1;

    const { data, error } = await supabase
      .from('subsidies')
      .select('id, title, summary, organization, fetched_at')
      .eq('is_active', true)
      .eq('crawl_status', 'published')
      .is('duplicate_of_id', null)
      .order('id', { ascending: true })
      .range(from, to);

    if (error) {
      throw new Error(`subsidies取得エラー: ${error.message}`);
    }

    const chunk = data || [];
    rows.push(...chunk);

    if (chunk.length < pageSize) break;
    from += pageSize;
  }

  return rows;
}

async function fetchAllPublishedColumns(supabase) {
  const pageSize = 1000;
  let from = 0;
  const rows = [];

  while (true) {
    const to = from + pageSize - 1;

    const { data, error } = await supabase
      .from('columns')
      .select('slug, published_at')
      .eq('is_published', true)
      .order('slug', { ascending: true })
      .range(from, to);

    if (error) {
      console.warn(`⚠️ columns取得エラー: ${error.message}`);
      return rows;
    }

    const chunk = data || [];
    rows.push(...chunk);

    if (chunk.length < pageSize) break;
    from += pageSize;
  }

  return rows;
}

async function fetchAllPublishedExpertArticles(supabase) {
  const pageSize = 1000;
  let from = 0;
  const rows = [];

  while (true) {
    const to = from + pageSize - 1;

    const { data, error } = await supabase
      .from('expert_articles')
      .select('slug, published_at, updated_at')
      .eq('status', 'published')
      .eq('is_active', true)
      .not('slug', 'is', null)
      .neq('slug', '')
      .order('slug', { ascending: true })
      .range(from, to);

    if (error) {
      console.warn(`⚠️ expert_articles取得エラー: ${error.message}`);
      return rows;
    }

    const chunk = data || [];
    rows.push(...chunk);

    if (chunk.length < pageSize) break;
    from += pageSize;
  }

  return rows;
}

async function main() {
  console.log('🚀 sitemap.xml 自動生成を開始します');
  console.log(`SITE_URL: ${SITE_URL}`);

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    throw new Error(
      'VITE_SUPABASE_URL または VITE_SUPABASE_ANON_KEY が見つかりません。.env.production を確認してください。'
    );
  }

  const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
  });

  const today = new Date().toISOString().slice(0, 10);

  const staticEntries = STATIC_ROUTES.filter((route) =>
    isIndexableSitemapPath(route.path)
  ).map((route) =>
    toUrlEntry({
      loc: buildUrl(route.path),
      lastmod: today,
      changefreq: route.changefreq,
      priority: route.priority,
    })
  );

  const subsidies = await fetchAllPublishedSubsidies(supabase);

  const indexableSubsidies = subsidies.filter(isIndexableSubsidy);
  const subsidyRouteMapCount = writeSubsidyRouteMap(indexableSubsidies);

  const subsidyEntries = indexableSubsidies
    .map((item) =>
      toUrlEntry({
        loc: buildUrl(`/subsidy/${item.id}`),
        lastmod: item.fetched_at || today,
        changefreq: 'weekly',
        priority: '0.8',
      })
    );

  const columns = await fetchAllPublishedColumns(supabase);

  const columnEntries = columns
    .filter((item) => item?.slug)
    .map((item) =>
      toUrlEntry({
        loc: buildUrl(`/column/${encodeURIComponent(item.slug)}`),
        lastmod: item.published_at || today,
        changefreq: 'monthly',
        priority: '0.7',
      })
    );

  const expertArticles = await fetchAllPublishedExpertArticles(supabase);

  const expertArticleEntries = expertArticles
    .filter((item) => item?.slug)
    .map((item) =>
      toUrlEntry({
        loc: buildUrl(`/expert-articles/${encodeURIComponent(item.slug)}`),
        lastmod: item.published_at || item.updated_at || today,
        changefreq: 'monthly',
        priority: '0.7',
      })
    );

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
>
${[...staticEntries, ...subsidyEntries, ...columnEntries, ...expertArticleEntries].join('\n')}
</urlset>
`;

  fs.writeFileSync(OUTPUT_PATH, xml, 'utf8');

  console.log('==============================');
  console.log('✅ sitemap.xml 生成完了');
  console.log(`出力先: ${OUTPUT_PATH}`);
  console.log(`静的ページ: ${staticEntries.length} 件`);
  console.log(`補助金詳細: ${subsidyEntries.length} 件`);
  console.log(`補助金詳細404判定マップ: ${subsidyRouteMapCount} 件`);
  console.log(`コラム詳細: ${columnEntries.length} 件`);
  console.log(`専門家記事詳細: ${expertArticleEntries.length} 件`);
  console.log(
    `合計: ${
      staticEntries.length +
      subsidyEntries.length +
      columnEntries.length +
      expertArticleEntries.length
    } 件`
  );
  console.log('==============================');
}

main().catch((err) => {
  console.error('❌ sitemap.xml 生成エラー:', err.message);
  process.exit(1);
});
